export const POST_ADMIN_SIGNIN_SUCCESS = "POST_ADMIN_SIGNIN_SUCCESS";
export const POST_ADMIN_SIGNIN_FAILE = "POST_ADMIN_SIGNIN_FAILE";
export const GET_USER_ADMIN_PAGE_SUCCESS = "GET_USER_ADMIN_PAGE_SUCCESS";
export const GET_USER_ADMIN_PAGE_FAILE = "GET_USER_ADMIN_PAGE_FAILE";
export const ADMIN_LOGOUT = "ADMIN_LOGOUT";
