export const GET_LIST_COURSE_SUCCESS = "GET_LIST_COURSE_SUCCESS";
export const GET_LIST_COURSE_FAILE = "GET_LIST_COURSE_FAILE";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILE = "GET_CATEGORIES_FAILE";
export const GET_COURSES_OF_CATEGORY_SUCCESS =
  "GET_COURSES_OF_CATEGORY_SUCCESS";
export const GET_COURSES_OF_CATEGORY_FAILE = "GET_COURSES_OF_CATEGORY_FAILE";
