export const GET_LIST_COURSE_SUCCESS = "GET_LIST_COURSE_SUCCESS";
export const GET_LIST_COURSE_FAILE = "GET_LIST_COURSE_FAILE";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILE = "GET_CATEGORIES_FAILE";
export const GET_COURSES_OF_CATEGORY_SUCCESS =
  "GET_COURSES_OF_CATEGORY_SUCCESS";
export const GET_COURSES_OF_CATEGORY_FAILE = "GET_COURSES_OF_CATEGORY_FAILE";
export const GET_COURSE_DETAIL_SUCCESS = "GET_COURSE_DETAIL_SUCCESS";
export const GET_COURSE_DETAIL_FAILE = "GET_COURSE_DETAIL_FAILE";
export const GET_SEARCH_COURSE_SUCCESS = "GET_SEARCH_COURSE_SUCCESS";
export const GET_SEARCH_COURSE_FAILE = "GET_SEARCH_COURSE_FAILE";
export const POST_CANCEL_REGISTER_SUCCESS = "POST_CANCEL_REGISTER_SUCCESS";
export const POST_CANCEL_REGISTER_FAILE = "POST_CANCEL_REGISTER_FAILE";
export const ADD_TO_CART_COURSE = "ADD_TO_CART_COURSE";
export const REMOVE_CART_COURSE = "REMOVE_CART_COURSE";
export const GET_SEARCH_KEY = "GET_SEARCH_KEY";
