export const DATA_USER_REGISTER = "DATA_USER_REGISTER";
export const DATA_COURSE_REGISTER = "DATA_COURSE_REGISTER";
export const POST_COURSE_NOT_REGISTER_SUCCESS =
  "POST_COURSE_NOT_REGISTER_SUCCESS";
export const POST_USER_NOT_REGISTER_SUCCESS = "POST_USER_NOT_REGISTER_SUCCESS";
export const POST_COURSE_CONFIRMED_SUCCESS = "POST_COURSE_CONFIRMED_SUCCESS";
export const POST_USER_CONFIRMED_SUCCESS = "POST_USER_CONFIRMED_SUCCESS";
export const POST_COURSE_PENDING_SUCCESS = "POST_COURSE_PENDING_SUCCESS";
export const POST_USER_PENDING_SUCCESS = "POST_USER_PENDING_SUCCESS";
export const POST_COURSE_REGISTER_SUCCESS = "POST_COURSE_REGISTER_SUCCESS";
export const POST_USER_REGISTER_SUCCESS = "POST_USER_REGISTER_SUCCESS";
export const POST_COURSE_CANCEL_REGISTER_SUCCESS =
  "POST_COURSE_CANCEL_REGISTER_SUCCESS";
export const KEY_REGISTER = "KEY_REGISTER";
