export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILE = "SIGNUP_FAILE";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAILE = "SIGNIN_FAILE";
export const LOGOUT = "LOGOUT";
export const CHANGE_PROFILE_SUCCESS = "CHANGE_PROFILE_SUCCESS";
export const CHANGE_PROFILE_FAILE = "CHANGE_PROFILE_FAILE";
